[build]
builder = "NIXPACKS"
buildCommand = "cd admin && pip install -r requirements.txt"

[deploy]
startCommand = "cd admin && gunicorn app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
